version: 2.1
orbs:
  node: circleci/node@1.1.6 # orb version
jobs:
  setup: # name of the job
    executor:
       name: node/default
    steps:
       - checkout # to checkout to the git branch
       - node/with-cache:
             run: npm install
workflows:    
   install_dependencies:    # name of workflow 
     jobs:                  # jobs to be performed in the workflow
      - setup               # the actual job
